### ISSUE TITLE
Since Update auth error 

### ISSUE THREAD

**Issue by nikestar98** [tgalal/yowsup#1172]
Hi I ve got a Question after the new WhatsApp Update I updated all my ENV stuff as explained in one thread. But now it still says: 

```
general: Login Failed, reason: not-authorized
Auth Error, reason not-authorized
```

How can I check if my Number is blocked?
##

**Comment by addodelgrossi** [comment]
I have the same error, since last week.

**Comment by addodelgrossi** [comment]
Resolved #1164

**Comment by blackjack4494** [comment]
the problem is still there for me at least and i also updated everything.
