### ISSUE TITLE
S40 is not supported anymore

### ISSUE THREAD

**Issue by jlguardi** [tgalal/yowsup#1384]
All my accounts have gotten not-authorized error.

I've changed to Android env and worked again but unsupported encryption pkmsg become a critical issue now

**Comment by cooper667** [comment]
```    _VERSION = "2.13.39"
    _OS_NAME= "S40"
    _OS_VERSION = "14.26"
    _DEVICE_NAME = "302"
    _MANUFACTURER = "Nokia"
    _TOKEN_STRING  = "PdA2DJyKoUrwLw1Bg6EIhzh502dF9noR9uFCllGk{phone}"```

**Comment by jegue** [comment]
any solution?
I am using AndroidYowsupEnv
CURRENT_ENV = AndroidYowsupEnv()

But still the same problem
yowsup-cli v2.0.13
Using yowsup v2.4.48

</response>

ADEBUG:yowsup.layers.logger.layer:rx:
<failure>
<not-authorized>
</not-authorized>
</failure>

**Comment by terminet85** [comment]
@cooper667 Same your version and token but not-authorized...

**Comment by terminet85** [comment]
@jlguardi I've tried to switch to Android, but I've got not-authorized.

`    _MD5_CLASSES = "7UDPOXwpiLBvEjT8uNwsuA=="
    _KEY = "eQV5aq/Cg63Gsq1sshN9T3gh+UUp0wIw0xgHYT1bnCjEqOJQKCRrWxdAe2yvsDeCJL+Y4G3PRD2HUF7oUgiGo8vGlNJOaux26k+A2F3hj8A="

    _VERSION = "2.12.440"
`
Are this updated?

**Comment by dazzzl** [comment]
@terminet85 same for me ... also requesting new password is not possible:
INFO:yowsup.common.http.warequest:{"status":"fail","reason":"incorrect","sms_length":6,"voice_length":6,"sms_wait":0,"voice_wait":0}

INFO:yowsup.common.http.warequest:{"status":"fail","reason":"no_routes","retry_after":3600,"sms_wait":3600,"voice_wait":3600}

status: fail
retry_after: 3600
reason: no_routes

**Comment by jlguardi** [comment]
@terminet85 Yes, I'm using now this version/key. Are your sure that you have correctly patched?
@cooper667 where have you get this version/key? It isn't in master neither develop/wa16

**Comment by jegue** [comment]
I got the sms and registration work fine! but the problem still the same
 not-authorized
and I re-register the number in a iphone 3 and works on whatsapp app on the iphone!
but not working anymore in yowsup.
 at least the number is not blocked for life!

**Comment by cooper667** [comment]
@jlguardi 
https://coderus.openrepos.net/whitesoft/whatsapp_scratch

**Comment by rigid** [comment]
@cooper667 thank you. That works for me.
Would someone please commit this?

**Comment by jlguardi** [comment]
@cooper667 Thanks, I'll PR this version info

**Comment by montemarcaldera** [comment]
@cooper667 What means each key?

**Comment by jlguardi** [comment]
In summary, to fix this issue, apply #1385 or use AndroidEnv (but some API is not still supported with Android)

**Comment by dazzzl** [comment]
AndroidEnv is not working for me .... however, the wa16 branch is working and so new tokens for S40 

strange....

**Comment by terminet85** [comment]
Are you sure you're resolving with https://coderus.openrepos.net/whitesoft/whatsapp_scratch ?
I've updated but I'll continue to got not-authorized

**Comment by montemarcaldera** [comment]
What means each key?

**Comment by jlguardi** [comment]
@terminet85 Yes, I've tested and login with S40 2.13.39
@dazzzl You should apply #1336 for Android

**Comment by dazzzl** [comment]
@jlguardi I have done this... I cloned your repo with the new branch

**Comment by terminet85** [comment]
Please aware #1336 _TOKEN_STRING is wrong, should be:
`    _TOKEN_STRING  = "PdA2DJyKoUrwLw1Bg6EIhzh502dF9noR9uFCllGk1456529096701{phone}"`

**Comment by msshapira** [comment]
@jlguardi Did you have to re-register your numbers? I was using Android
env. Merged in https://coderus.openrepos.net/whitesoft/whatsapp_scratch but
still didn't work. I also tried #1336 - but nada

**Comment by terminet85** [comment]
@msshapira #1336 have a wrong _TOKEN_STRING

**Comment by msshapira** [comment]
@terminet85  I tried the one you suggested, but still not authorized...

**Comment by terminet85** [comment]
@msshapira 
`    _VERSION = "2.13.39"
    _OS_NAME= "S40"
    _OS_VERSION = "14.26"
    _DEVICE_NAME = "Nokia302"
    _TOKEN_STRING  = "PdA2DJyKoUrwLw1Bg6EIhzh502dF9noR9uFCllGk1456529096701{phone}"
    _AXOLOTL = True
`

**Comment by msshapira** [comment]
Doesn't seem to work. I've also tried (android):

    _SIGNATURE = "MIIDMjCCAvCgAwIBAgIETCU2pDALBgcqhkjOOAQDBQAwfDELMAkGA1UEBhMCVVMxEzARBgNVBAgTCkNhbGlmb3JuaWExFDASBgNV" \
        "BAcTC1NhbnRhIENsYXJhMRYwFAYDVQQKEw1XaGF0c0FwcCBJbmMuMRQwEgYDVQQLEwtFbmdpbmVlcmluZzEUMBIGA1UEAxMLQnJ" \
        "pYW4gQWN0b24wHhcNMTAwNjI1MjMwNzE2WhcNNDQwMjE1MjMwNzE2WjB8MQswCQYDVQQGEwJVUzETMBEGA1UECBMKQ2FsaWZvcm5" \
        "pYTEUMBIGA1UEBxMLU2FudGEgQ2xhcmExFjAUBgNVBAoTDVdoYXRzQXBwIEluYy4xFDASBgNVBAsTC0VuZ2luZWVyaW5nMRQwEg" \
        "YDVQQDEwtCcmlhbiBBY3RvbjCCAbgwggEsBgcqhkjOOAQBMIIBHwKBgQD9f1OBHXUSKVLfSpwu7OTn9hG3UjzvRADDHj+AtlEm" \
        "aUVdQCJR+1k9jVj6v8X1ujD2y5tVbNeBO4AdNG/yZmC3a5lQpaSfn+gEexAiwk+7qdf+t8Yb+DtX58aophUPBPuD9tPFHsMCN" \
        "VQTWhaRMvZ1864rYdcq7/IiAxmd0UgBxwIVAJdgUI8VIwvMspK5gqLrhAvwWBz1AoGBAPfhoIXWmz3ey7yrXDa4V7l5lK+7+jr" \
        "qgvlXTAs9B4JnUVlXjrrUWU/mcQcQgYC0SRZxI+hMKBYTt88JMozIpuE8FnqLVHyNKOCjrh4rs6Z1kW6jfwv6ITVi8ftiegEkO" \
        "8yk8b6oUZCJqIPf4VrlnwaSi2ZegHtVJWQBTDv+z0kqA4GFAAKBgQDRGYtLgWh7zyRtQainJfCpiaUbzjJuhMgo4fVWZIvXHaS" \
        "HBU1t5w//S0lDK2hiqkj8KpMWGywVov9eZxZy37V26dEqr/c2m5qZ0E+ynSu7sqUD7kGx/zeIcGT0H+KAVgkGNQCo5Uc0koLRW" \
        "YHNtYoIvt5R3X6YZylbPftF/8ayWTALBgcqhkjOOAQDBQADLwAwLAIUAKYCp0d6z4QQdyN74JDfQ2WCyi8CFDUM4CaNB+ceVXd" \
        "KtOrNTQcc0e+t"

    _MD5_CLASSES = "yLVHACNiUpjl692c0/WzRQ=="
    _KEY = "eQV5aq/Cg63Gsq1sshN9T3gh+UUp0wIw0xgHYT1bnCjEqOJQKCRrWxdAe2yvsDeCJL+Y4G3PRD2HUF7oUgiGo8vGlNJOaux26k+A2F3hj8A="

    _VERSION = "2.12.544"
    _OS_NAME = "Android"
    _OS_VERSION = "4.3"
    _DEVICE_NAME = "GalaxyS3"
    _AXOLOTL = True

**Comment by terminet85** [comment]
@msshapira If you've applied the path to use Android version you need to roll-back

**Comment by eduardobento** [comment]
Like @cooper667 said:

_VERSION = "2.13.39" 
_TOKEN_STRING = "PdA2DJyKoUrwLw1Bg6EIhzh502dF9noR9uFCllGk{phone}"

Worked for me too. Look, the _TOKEN_STRING do not have timestamp before {phone} tag. This is the diference for me!

**Comment by yniv** [comment]
after updating the token (from the pull request) i can connect but i start to get these errors:
```
Traceback (most recent call last):
  File "/home/bumptestlin/server/server.py", line 78, in <module>
    asyncore.loop()
  File "/usr/lib/python2.7/asyncore.py", line 216, in loop
    poll_fun(timeout, map)
  File "/usr/lib/python2.7/asyncore.py", line 156, in poll
    read(obj)
  File "/usr/lib/python2.7/asyncore.py", line 87, in read
    obj.handle_error()
  File "/usr/lib/python2.7/asyncore.py", line 83, in read
    obj.handle_read_event()
  File "/usr/lib/python2.7/asyncore.py", line 449, in handle_read_event
    self.handle_read()
  File "/home/bumptestlin/server/venv-yowsapp/local/lib/python2.7/site-packages/yowsup/layers/network/layer.py", line 86, in handle_read
    self.receive(data)
  File "/home/bumptestlin/server/venv-yowsapp/local/lib/python2.7/site-packages/yowsup/layers/network/layer.py", line 94, in receive
    self.toUpper(data)
  File "/home/bumptestlin/server/venv-yowsapp/local/lib/python2.7/site-packages/yowsup/layers/__init__.py", line 59, in toUpper
    self.__upper.receive(data)
  File "/home/bumptestlin/server/venv-yowsapp/local/lib/python2.7/site-packages/yowsup/layers/stanzaregulator/layer.py", line 28, in receive
    self.processReceived()
  File "/home/bumptestlin/server/venv-yowsapp/local/lib/python2.7/site-packages/yowsup/layers/stanzaregulator/layer.py", line 48, in processReceived
    self.toUpper(oneMessageData)
  File "/home/bumptestlin/server/venv-yowsapp/local/lib/python2.7/site-packages/yowsup/layers/__init__.py", line 59, in toUpper
    self.__upper.receive(data)
  File "/home/bumptestlin/server/venv-yowsapp/local/lib/python2.7/site-packages/yowsup/layers/auth/layer_crypt.py", line 63, in receive
    self.toUpper(payload)
  File "/home/bumptestlin/server/venv-yowsapp/local/lib/python2.7/site-packages/yowsup/layers/__init__.py", line 59, in toUpper
    self.__upper.receive(data)
  File "/home/bumptestlin/server/venv-yowsapp/local/lib/python2.7/site-packages/yowsup/layers/coder/layer.py", line 35, in receive
    self.toUpper(node)
  File "/home/bumptestlin/server/venv-yowsapp/local/lib/python2.7/site-packages/yowsup/layers/__init__.py", line 59, in toUpper
    self.__upper.receive(data)
  File "/home/bumptestlin/server/venv-yowsapp/local/lib/python2.7/site-packages/yowsup/layers/logger/layer.py", line 14, in receive
    self.toUpper(data)
  File "/home/bumptestlin/server/venv-yowsapp/local/lib/python2.7/site-packages/yowsup/layers/__init__.py", line 59, in toUpper
    self.__upper.receive(data)
  File "/home/bumptestlin/server/venv-yowsapp/local/lib/python2.7/site-packages/yowsup/layers/axolotl/layer.py", line 117, in receive
    self.onMessage(protocolTreeNode)
  File "/home/bumptestlin/server/venv-yowsapp/local/lib/python2.7/site-packages/yowsup/layers/axolotl/layer.py", line 139, in onMessage
    self.handleEncMessage(protocolTreeNode)
  File "/home/bumptestlin/server/venv-yowsapp/local/lib/python2.7/site-packages/yowsup/layers/axolotl/layer.py", line 222, in handleEncMessage
    self.handlePreKeyWhisperMessage(node)
  File "/home/bumptestlin/server/venv-yowsapp/local/lib/python2.7/site-packages/yowsup/layers/axolotl/layer.py", line 267, in handlePreKeyWhisperMessage
    self.toUpper(node)
  File "/home/bumptestlin/server/venv-yowsapp/local/lib/python2.7/site-packages/yowsup/layers/__init__.py", line 59, in toUpper
    self.__upper.receive(data)
  File "/home/bumptestlin/server/venv-yowsapp/local/lib/python2.7/site-packages/yowsup/layers/__init__.py", line 169, in receive
    s.receive(data)
  File "/home/bumptestlin/server/venv-yowsapp/local/lib/python2.7/site-packages/yowsup/layers/__init__.py", line 105, in receive
    recv(node)
  File "/home/bumptestlin/server/venv-yowsapp/local/lib/python2.7/site-packages/yowsup/layers/protocol_messages/layer.py", line 21, in recvMessageStanza
    self.toUpper(entity)
  File "/home/bumptestlin/server/venv-yowsapp/local/lib/python2.7/site-packages/yowsup/layers/__init__.py", line 59, in toUpper
    self.__upper.receive(data)
  File "/home/bumptestlin/server/venv-yowsapp/local/lib/python2.7/site-packages/yowsup/layers/interface/interface.py", line 98, in receive
    self.callbacks[entityType](entity)
  File "/home/bumptestlin/server/bumpyard_layer.py", line 213, in onMessage
    'message': messageOut.encode('latin-1').decode() if sys.version_info >= (3, 0) else messageOut})
  File "/usr/lib/python2.7/json/__init__.py", line 243, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python2.7/json/encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python2.7/json/encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
UnicodeDecodeError: 'utf8' codec can't decode byte 0x9e in position 0: invalid start byte
```
and it get disconnected after recieving 1 message
anyone know's about this?

**Comment by jlguardi** [comment]
I've edited my PR (#1385) due to timestamp should be in _TOKEN_STRING or register doesn't works (if S40 is used for register).

I've tested registration and login and both worked.

PS: re-registration is not required to use the new credentials but if you started the process to re-register your phone number, probably you need to remove de $HOME/.yowsup/$phone/id file due to id differs between Android and Nokia. 

Related with #1389

**Comment by cfenollosa** [comment]
Hi @jlguardi, after applying your latest patches (new S40 env and latest token) I suddenly can't receive messages anymore.

The stack connects and the code appears as online to other users, but messages can't be received.

**Comment by jhonnyvey** [comment]
Tried re-registration and after this not receive SMS from whatsapp server.
Any idea? Tried in linux and WART in Windows

**Comment by kw005** [comment]
same problem 

INFO:yowsup.common.http.warequest:{"status":"fail","reason":"no_routes","retry_after":3600,"sms_wait":3600,"voice_wait":3600}

status: fail
retry_after: 3600

**Comment by mikkolindfors** [comment]
Where can I find fixed zip? I managed to register with new card yesterday but now I can't login. same error as above.

**Comment by mikkolindfors** [comment]
And thanks for this sw, great job

**Comment by mikkolindfors** [comment]
Any update on this?

**Comment by snappshare** [comment]
got the same problem, is there a solution? :.c

**Comment by jlguardi** [comment]
@snappshare update your code. It is fixed.

**Comment by snappshare** [comment]
@jlguardi Hm, still get the same error.
Could it be that my number got blocked? (I confirmed it today.)

**Comment by snappshare** [comment]
I have
yowsup-cli version 2.0.15
and
yowsup version 2.4.102
is it outdated? Cant find a newer version.

**Comment by jlguardi** [comment]
You have th current tgalal master so y are up to date. 
Check if you are banned (register again).

**Comment by snappshare** [comment]
@jlguardi 
thx for reply.
Nope, i´m not banned :/
I checked the password several times and refreshed it.
Here is what i get with my second mobile (not using whatsapp but tried it with it before.):
status: ok
kind: free
pw: veqbk0iwG8rCJO+1ndUAol*****=
price: 0,89 €
price_expiration: 1462706202
currency: EUR
cost: 0.89
expiration: 4444444444.0
login: 491625762695
type: existing

My config:
cc=49
phone=49016257*****
id=0000000000
password=veqbk0iwG8rCJO+1ndUAol*****=

And a log:
root@debian:/usr/local/bin# python yowsup-cli demos -c /opt/yowsup-config/yowsup.config -e -d
yowsup-cli  v2.0.15
yowsup      v2.4.102

Copyright (c) 2012-2016 Tarek Galal
http://www.openwhatsapp.org

This software is provided free of charge. Copying and redistribution is
encouraged.

If you appreciate this software and you would like to support future
development please consider donating:
http://openwhatsapp.org/yowsup/donate


DEBUG:yowsup.env.env:Env not set, setting it to android
DEBUG:yowsup.env.env:Current env changed to android 
DEBUG:yowsup.stacks.yowstack:Initializing stack
DEBUG:yowsup.stacks.yowstack:Constructed Network Layer
DEBUG:yowsup.stacks.yowstack:Constructed Stanza Regulator Layer
DEBUG:yowsup.stacks.yowstack:Constructed Crypt Layer
DEBUG:yowsup.stacks.yowstack:Constructed Coder Layer
DEBUG:yowsup.stacks.yowstack:Constructed Logger Layer
DEBUG:yowsup.stacks.yowstack:Constructed Axolotl Layer
DEBUG:yowsup.stacks.yowstack:Constructed Authentication Layer - Messages Layer - Receipt Layer - Ack Layer - Presence Layer - Ib Layer - Iq Layer - notification Ib Layer - Iq Layer - Chatstate Layer - call Layer - Groups Iq Layer - Media Layer - Privacy Layer - Profiles Layer
DEBUG:yowsup.stacks.yowstack:Constructed Interface Layer
DEBUG:yowsup.layers.network.layer:Connecting to e9.whatsapp.net:443
DEBUG:yowsup.layers.logger.layer:tx:
<stream:features>
<readreceipts>
</readreceipts>
<groups_v2>
</groups_v2>
<privacy>
</privacy>
<presence>
</presence>
</stream:features>

DEBUG:yowsup.layers.logger.layer:tx:
<auth passive="true" user="4901625762695" mechanism="WAUTH-2">
</auth>

DEBUG:yowsup.layers.logger.layer:rx:
<stream:features>
</stream:features>

DEBUG:yowsup.layers.logger.layer:rx:
<challenge>
=��m�� X�ǣ�}�uzu�=I
HEX:3dbdca6dedbd185899c7a3917dc4757a75ec3d49
</challenge>

DEBUG:yowsup.layers.logger.layer:tx:
<response xmlns="urn:ietf:params:xml:ns:xmpp-sasl">
� {r /�eJ y�� 7& ˫�d1�ۅ�� y ��^+�~!jr2
HEX:bb137b721f7f062fc5654a1479e48b06372615cbab8164318bdb85b4da1e791b8f261ea5c95e2b9ded087e216a7232
</response>

DEBUG:yowsup.layers.logger.layer:rx:
<failure>
<not-authorized>
</not-authorized>
</failure>

DEBUG:yowsup.layers.network.layer:Disconnected, reason: Authentication Failure
Authentication Error: not-authorized

**Comment by rump1992** [comment]
same problem here
