### ISSUE TITLE
AuthError: not-authorized 

### ISSUE THREAD

**Issue by carlosfelipe29** [tgalal/yowsup#1398]
Hi, Guys, Who knows about it?, maybe Whatsapp is blocking a third person applications ? @tgalal @gauravdave01  @jlguardi 

I got the same problem, with two systems(two SIM CARDS) that I have running on a two BeagleBone Black. Today Suddenly stop send mgs:

general: Login Failed, reason: not-authorized
Auth Error, reason not-authorized

Using the Yowsup-cli occur the same thing. With those examples like runTest.py that re-send the same message, as well.

I reinstalled all. pip install yowsup2 --upgrade, download the yowsup from Tgalal by git,

With the SAME RESULT. If I ask fr a requestCode:

INFO:yowsup.common.http.warequest:{"status":"fail","reason":"old_version"}

status: fail
reason: old_version

It happens again and again.

I fixed it as @jlguardi suggest, changing ENV, I do al the changes, afeter that  python setup.py install,  I got new credentials BUT when I triy to log in appears again: (with or without yowsup-cli)

*Login Failed, reason: not-authorized
*Auth Error, reason not-authorized

Someone have any idea, We have to wait Whatsapp unblocked or something...

thanks

**Comment by antoniespinosa** [comment]
try to use https://github.com/jlguardi/yowsup/tree/Android_2.12.440 this fork with android env (it works for me) register with yowsup-cli, after you get the pw, use the master branch, (because not all things are supported in android env). Probably you will have a problem (not-authorized) you must set the new token in s40env. 
edit yowsup/env/env_s40.py line 5

_VERSION = "2.13.39"
    _OS_NAME= "S40"
    _OS_VERSION = "14.26"
    _DEVICE_NAME = "Nokia302"
    _TOKEN_STRING = "PdA2DJyKoUrwLw1Bg6EIhzh502dF9noR9uFCllGk{phone}"
    _AXOLOTL = True

after that you will have a problem with the plain text messages (garbage after the text) you must rewrite the function unpadV2Plaintext  with those->
def decodeInt7bit(self, string):
        idx = 0
        while ord(string[idx]) >= 128:
            idx += 1
        consumedBytes = idx + 1
        value = 0
        while idx >= 0:
            value <<= 7
            value += ord(string[idx]) % 128
            idx -= 1
        return value, consumedBytes

    def unpadV2Plaintext(self, v2plaintext):
        end = -ord(v2plaintext[-1]) # length of the left padding
        length,consumed = self.decodeInt7bit(v2plaintext[1:])
        return v2plaintext[1+consumed:end]

It works for me

**Comment by fabiobpinto** [comment]
antoniespinosa thanks work for me

**Comment by carlosfelipe29** [comment]
@antoniespinosa   thanks you.

It really helps me,  I am On line again.  But the format on 

def unpadV2Plaintext(self, v2plaintext):
    end = -ord(v2plaintext[-1]) # length of the left padding
    length,consumed = self.decodeInt7bit(v2plaintext[1:])
    return v2plaintext[1+consumed:end

what file Do I have to change??

with the Git of  https://github.com/jlguardi/yowsup/tree/Android_2.12.440 , I have to modify manually, after that, it works.

**Comment by antoniespinosa** [comment]
Sorry, layers/axolotl/layer.py

**Comment by carlosfelipe29** [comment]
Hi,  the  new fuction is:

def decodeInt7bit(self, string):
        idx = 0
        while ord(string[idx]) >= 128:
                idx += 1
                consumedBytes = idx + 1
                value = 0
                while idx >= 0:
                        value <<= 7
                        value += ord(string[idx]) % 128
                        idx -= 1
        return value, consumedBytes

with this identation??....


thank you,  is it necessary to rebuild and install ?,

**Comment by antoniespinosa** [comment]
`    def decodeInt7bit(self, string):
        idx = 0
        while ord(string[idx]) >= 128:
            idx += 1
        consumedBytes = idx + 1
        value = 0
        while idx >= 0:
            value <<= 7
            value += ord(string[idx]) % 128
            idx -= 1
        return value, consumedBytes`

**Comment by carlosfelipe29** [comment]
Hi, It still un format the answer.

maybe it is the identation of the function. 

Do you mean to do again python setup.py install .

thanks

**Comment by DonkeyHot** [comment]
@antoniespinosa thanks, it is started to works for me

But I still have error & warning messages
```
2016-03-24 11:49:10,923 ERROR yowsup.layers.axolotl.layer Received message with old counter: 1, 0
2016-03-24 11:49:10,923 WARNING yowsup.layers.axolotl.layer Going to send the delivery receipt myself !
```

It seems to be only when my application received media messages (images, locations etc) sent from WhatsApp client for iOS (my be not the only). If I sent thees types of message from web-client  (etc web.whatsapp.com)  the error does not appear.

**Comment by biji** [comment]
@antoniespinosa thanks it works

but like @DonkeyHot , receiving media message failed, but sending success

**Comment by DonkeyHot** [comment]
Switching from Nokia to Android env solves the problem for me

**Comment by yniv** [comment]
@DonkeyHot what yowsup version do you use?

**Comment by DonkeyHot** [comment]
I used forked yowsup from @jlguardi

https://github.com/jlguardi/yowsup

**Comment by yniv** [comment]
@DonkeyHot does this version really solve encrypted image messages??? @jlguardi ??
on what environment are you running? s40 or android?

**Comment by jlguardi** [comment]
I'm using android env. We need to fix axolotl/layer for media and also group encrypted messages.
For that, python-axolotl should be also edited.
As pointed @mgp25 the right way is to port chatapi to python. 
If you try your code, be careful due to images from whatsapp web connected connected to oficial android are not encrypted. So try from an android app.

**Comment by yniv** [comment]
@jlguardi the android env is working??? so only web connected to official whatsapp images are working in the android env?
well, anyway, currently i don't know if someone is working on porting from chat-api... so looks like there won't be a solution anytime soon :-/

**Comment by pablosouza10** [comment]
Work for me running "**git clone https://github.com/jlguardi/yowsup.git**" and change the path for yowsup-cli for the new downloaded!

**Comment by Lijo050** [comment]
@pablosouza10 @jlguardi @DonkeyHot After clonning https://github.com/jlguardi/yowsup.git and then registering again, I could successfully login. But I'm getting the error `ERROR:yowsup.layers.axolotl.layer:No valid sessionsBad Mac!
ERROR:yowsup.layers.axolotl.layer:No such signedprekeyrecord! 0`
I can't read any message sent to my registered number and the error shown is `ERROR:yowsup.layers.axolotl.layer:No session for: 919*********, 1`

**Comment by pablosouza10** [comment]
@lijo050 Are you using the parameter -M (Example) ...demos -M -s numer ...

**Comment by Lijo050** [comment]
@pablosouza10  No, I didn't add -M. But now the error changed to `File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.4.48-py2.7.egg/yowsup/layers/axolotl/protocolentities/message_encrypted.py", line 24, in setEncProps
    assert encType in "pkmsg", "msg"
AssertionError: msg
make: *** [run] Error 1`

**Comment by jlguardi** [comment]
@Lijo050 Due to missing square brackets arround "pkmsg","msg"

**Comment by Lijo050** [comment]
@jlguardi Could you please mention file should i modify

**Comment by thundergreen** [comment]
/usr/local/lib/python2.7/dist-packages/yowsup2-2.4.48-py2.7.egg/yowsup/layers/axolotl/protocolentities/message_encrypted.py",
line 24

Thorsten Fröhlich
Am 25.03.2016 14:28 schrieb "Lijo Johny" <notifications@github.com>:

**Comment by Lijo050** [comment]
@jlguardi @thundergreen  is `["pkmsg","msg"]` in yowsup/layers/axolotl/protocolentities/message_encrypted.py  enough because I'm still getting the error

**Comment by Lijo050** [comment]
In private messages, I can't send message from yowsup back to phone while the other way  is working good. The error is
`[919*******5@s.whatsapp.net(25-03-2016 20:52)]:[4B520CFF05F1AD3CDA96AF044527F6]	 @help
DEBUG:yowsup.layers.logger.layer:tx:
<receipt to="919******5@s.whatsapp.net" id="4B520CFF05F1AD3CDA96AF044527F6">
</receipt>

Message 4B520CFF05F1AD3CDA96AF044527F6: Sent delivered receipt
[connected]:
Message:
ID: 1458919331-1
To: 919*******5@s.whatsapp.net
Type:  text
Timestamp: 1458919331
Body: None

Traceback (most recent call last):
  File "/usr/local/bin/yowsup-cli", line 5, in <module>
    pkg_resources.run_script('yowsup2==2.4.48', 'yowsup-cli')
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 528, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1394, in run_script
    execfile(script_filename, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.4.48-py2.7.egg/EGG-INFO/scripts/yowsup-cli", line 323, in <module>
    if not parser.process():
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.4.48-py2.7.egg/EGG-INFO/scripts/yowsup-cli", line 227, in process
    self.startCmdline()
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.4.48-py2.7.egg/EGG-INFO/scripts/yowsup-cli", line 255, in startCmdline
    stack.start()
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.4.48-py2.7.egg/yowsup/demos/cli/stack.py", line 25, in start
    self.stack.loop(timeout = 0.5, discrete = 0.5)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.4.48-py2.7.egg/yowsup/stacks/yowstack.py", line 187, in loop
    asyncore.loop(*args, **kwargs)
  File "/usr/lib/python2.7/asyncore.py", line 216, in loop
    poll_fun(timeout, map)
  File "/usr/lib/python2.7/asyncore.py", line 156, in poll
    read(obj)
  File "/usr/lib/python2.7/asyncore.py", line 87, in read
    obj.handle_error()
  File "/usr/lib/python2.7/asyncore.py", line 83, in read
    obj.handle_read_event()
  File "/usr/lib/python2.7/asyncore.py", line 449, in handle_read_event
    self.handle_read()
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.4.48-py2.7.egg/yowsup/layers/network/layer.py", line 86, in handle_read
    self.receive(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.4.48-py2.7.egg/yowsup/layers/network/layer.py", line 94, in receive
    self.toUpper(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.4.48-py2.7.egg/yowsup/layers/__init__.py", line 59, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.4.48-py2.7.egg/yowsup/layers/stanzaregulator/layer.py", line 28, in receive
    self.processReceived()
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.4.48-py2.7.egg/yowsup/layers/stanzaregulator/layer.py", line 48, in processReceived
    self.toUpper(oneMessageData)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.4.48-py2.7.egg/yowsup/layers/__init__.py", line 59, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.4.48-py2.7.egg/yowsup/layers/auth/layer_crypt.py", line 63, in receive
    self.toUpper(payload)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.4.48-py2.7.egg/yowsup/layers/__init__.py", line 59, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.4.48-py2.7.egg/yowsup/layers/coder/layer.py", line 35, in receive
    self.toUpper(node)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.4.48-py2.7.egg/yowsup/layers/__init__.py", line 59, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.4.48-py2.7.egg/yowsup/layers/logger/layer.py", line 14, in receive
    self.toUpper(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.4.48-py2.7.egg/yowsup/layers/__init__.py", line 59, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.4.48-py2.7.egg/yowsup/layers/axolotl/layer.py", line 118, in receive
    self.onMessage(protocolTreeNode)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.4.48-py2.7.egg/yowsup/layers/axolotl/layer.py", line 140, in onMessage
    self.handleEncMessage(protocolTreeNode)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.4.48-py2.7.egg/yowsup/layers/axolotl/layer.py", line 223, in handleEncMessage
    self.handlePreKeyWhisperMessage(node)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.4.48-py2.7.egg/yowsup/layers/axolotl/layer.py", line 268, in handlePreKeyWhisperMessage
    self.toUpper(node)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.4.48-py2.7.egg/yowsup/layers/__init__.py", line 59, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.4.48-py2.7.egg/yowsup/layers/__init__.py", line 169, in receive
    s.receive(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.4.48-py2.7.egg/yowsup/layers/__init__.py", line 105, in receive
    recv(node)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.4.48-py2.7.egg/yowsup/layers/protocol_messages/layer.py", line 21, in recvMessageStanza
    self.toUpper(entity) 
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.4.48-py2.7.egg/yowsup/layers/__init__.py", line 59, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.4.48-py2.7.egg/yowsup/layers/interface/interface.py", line 98, in receive
    self.callbacks[entityType](entity)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.4.48-py2.7.egg/yowsup/demos/cli/layer.py", line 740, in onMessage
    self.message_send(message_sender, self.startMenu(message.getBody(),message_sender))
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.4.48-py2.7.egg/yowsup/demos/cli/layer.py", line 547, in message_send
    self.toLower(outgoingMessage)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.4.48-py2.7.egg/yowsup/layers/__init__.py", line 63, in toLower
    self.__lower.send(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.4.48-py2.7.egg/yowsup/layers/__init__.py", line 173, in send
    s.send(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.4.48-py2.7.egg/yowsup/layers/__init__.py", line 111, in send
    send(entity)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.4.48-py2.7.egg/yowsup/layers/protocol_messages/layer.py", line 15, in sendMessageEntity
    self.entityToLower(entity)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.4.48-py2.7.egg/yowsup/layers/__init__.py", line 115, in entityToLower
    self.toLower(entity.toProtocolTreeNode())
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.4.48-py2.7.egg/yowsup/layers/__init__.py", line 63, in toLower
    self.__lower.send(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.4.48-py2.7.egg/yowsup/layers/axolotl/layer.py", line 108, in send
    self.handlePlaintextNode(node)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.4.48-py2.7.egg/yowsup/layers/axolotl/layer.py", line 185, in handlePlaintextNode
    padded.extend(self.encodeInt7bit(len(plaintext)))
TypeError: object of type 'NoneType' has no len()
make: *** [run] Error 1`

**Comment by Lijo050** [comment]
@jlguardi Now again I'm getting `general: Login Failed, reason: not-authorized
DEBUG:yowsup.layers.network.layer:Disconnected, reason: Authentication Failure
Auth Error, reason not-authorized` after cloning your repo https://github.com/jlguardi/yowsup.git. So please look into it.

**Comment by tgalal** [comment]
Update to latest version should fix the auth problem

**Comment by flayla** [comment]
@tgalal should we re-register? updated and still get assert encType in "pkmsg", "msg"

**Comment by jlguardi** [comment]
@flayla you are getting skmsg (group encrypted messages) which isn't supported by the API yet. It's WIP and you can wait or use unestable develop branch or my master.

**Comment by flayla** [comment]
@jlguardi Thanks! so i'll patiently wait for an update :)
But how do I "get and ack" all messages w/o handling then so I wont get the exception when I try to use demos -e / demos -y and /L

**Comment by jlguardi** [comment]
Search "too many reries" in axolotl/layer.py and copy these lines.

De: flayla
Enviado: viernes, 1 de abril de 2016 17:08
Para: tgalal/yowsup
Responder a: tgalal/yowsup
CC: jlguardi
Asunto: Re: [tgalal/yowsup] AuthError: not-authorized (#1398)


@jlguardi Thanks! so i'll patiently wait for an update :)
But how do I "get and ack" all messages w/o handling then so I wont get the exception when I try to use demos -e / demos -y and /L

---

**Comment by flayla** [comment]
@jlguardi thanks for the very quick responses!
I *think* i'm using you're branch (used apt-get yowsup2)
I'm a real noob with Linux and Python. and currently try to perform simple actions with the client.

But even without groups. echo client is half working.
text is echoed back and voice notes are echoed back.
but I get exception when client receive media/location/contact

error for media: AttributeError: 'NoneType' object has no attribute 'getAttributeValue'
