### ISSUE TITLE
About Acks

### ISSUE THREAD

**Issue by Gab0** [tgalal/yowsup#1464]
I'm working to solve a issue I got with acks. So I need a bit of information, if anyone knows: 
To send a proper ack to the server, the received message must be decrypted first? 

I'm sending acks on non-decrypted skmsgs and pkmsgs, and the server sends them to me again everytime I log in. Thanks..

**Comment by jlguardi** [comment]
See my master where ack issues are fixed.

**Comment by Gab0** [comment]
Just installed your master and logged in, receiving the messages:

`Traceback (most recent call last):
  File "/usr/bin/yowsup-cli", line 4, in <module>
    __import__('pkg_resources').run_script('yowsup2==2.4.48', 'yowsup-cli')
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 719, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 1483, in run_script
    exec(code, namespace, namespace)
  File "/usr/lib/python3.5/site-packages/yowsup2-2.4.48-py3.5.egg/EGG-INFO/scripts/yowsup-cli", line 324, in <module>
    if not parser.process():
  File "/usr/lib/python3.5/site-packages/yowsup2-2.4.48-py3.5.egg/EGG-INFO/scripts/yowsup-cli", line 228, in process
    self.startCmdline()
  File "/usr/lib/python3.5/site-packages/yowsup2-2.4.48-py3.5.egg/EGG-INFO/scripts/yowsup-cli", line 256, in startCmdline
    stack.start()
  File "/usr/lib/python3.5/site-packages/yowsup2-2.4.48-py3.5.egg/yowsup/demos/cli/stack.py", line 27, in start
    self.stack.loop(timeout = 0.5, discrete = 0.5)
  File "/usr/lib/python3.5/site-packages/yowsup2-2.4.48-py3.5.egg/yowsup/stacks/yowstack.py", line 187, in loop
    asyncore.loop(*args, **kwargs)
  File "/usr/lib/python3.5/asyncore.py", line 203, in loop
    poll_fun(timeout, map)
  File "/usr/lib/python3.5/asyncore.py", line 150, in poll
    read(obj)
  File "/usr/lib/python3.5/asyncore.py", line 87, in read
    obj.handle_error()
  File "/usr/lib/python3.5/asyncore.py", line 83, in read
    obj.handle_read_event()
  File "/usr/lib/python3.5/asyncore.py", line 423, in handle_read_event
    self.handle_read()
  File "/usr/lib/python3.5/site-packages/yowsup2-2.4.48-py3.5.egg/yowsup/layers/network/layer.py", line 102, in handle_read
    self.receive(data)
  File "/usr/lib/python3.5/site-packages/yowsup2-2.4.48-py3.5.egg/yowsup/layers/network/layer.py", line 110, in receive
    self.toUpper(data)
  File "/usr/lib/python3.5/site-packages/yowsup2-2.4.48-py3.5.egg/yowsup/layers/__init__.py", line 75, in toUpper
    self.__upper.receive(data)
  File "/usr/lib/python3.5/site-packages/yowsup2-2.4.48-py3.5.egg/yowsup/layers/stanzaregulator/layer.py", line 29, in receive
    self.processReceived()
  File "/usr/lib/python3.5/site-packages/yowsup2-2.4.48-py3.5.egg/yowsup/layers/stanzaregulator/layer.py", line 49, in processReceived
    self.toUpper(oneMessageData)
  File "/usr/lib/python3.5/site-packages/yowsup2-2.4.48-py3.5.egg/yowsup/layers/__init__.py", line 75, in toUpper
    self.__upper.receive(data)
  File "/usr/lib/python3.5/site-packages/yowsup2-2.4.48-py3.5.egg/yowsup/layers/auth/layer_crypt.py", line 65, in receive
    self.toUpper(payload)
  File "/usr/lib/python3.5/site-packages/yowsup2-2.4.48-py3.5.egg/yowsup/layers/__init__.py", line 75, in toUpper
    self.__upper.receive(data)
  File "/usr/lib/python3.5/site-packages/yowsup2-2.4.48-py3.5.egg/yowsup/layers/coder/layer.py", line 35, in receive
    self.toUpper(node)
  File "/usr/lib/python3.5/site-packages/yowsup2-2.4.48-py3.5.egg/yowsup/layers/__init__.py", line 75, in toUpper
    self.__upper.receive(data)
  File "/usr/lib/python3.5/site-packages/yowsup2-2.4.48-py3.5.egg/yowsup/layers/logger/layer.py", line 14, in receive
    self.toUpper(data)
  File "/usr/lib/python3.5/site-packages/yowsup2-2.4.48-py3.5.egg/yowsup/layers/__init__.py", line 75, in toUpper
    self.__upper.receive(data)
  File "/usr/lib/python3.5/site-packages/yowsup2-2.4.48-py3.5.egg/yowsup/layers/axolotl/layer.py", line 132, in receive
    self.onMessage(protocolTreeNode)
  File "/usr/lib/python3.5/site-packages/yowsup2-2.4.48-py3.5.egg/yowsup/layers/axolotl/layer.py", line 156, in onMessage
    self.toUpper(protocolTreeNode)
  File "/usr/lib/python3.5/site-packages/yowsup2-2.4.48-py3.5.egg/yowsup/layers/__init__.py", line 75, in toUpper
    self.__upper.receive(data)
  File "/usr/lib/python3.5/site-packages/yowsup2-2.4.48-py3.5.egg/yowsup/layers/__init__.py", line 188, in receive
    s.receive(data)
  File "/usr/lib/python3.5/site-packages/yowsup2-2.4.48-py3.5.egg/yowsup/layers/__init__.py", line 124, in receive
    recv(node)
  File "/usr/lib/python3.5/site-packages/yowsup2-2.4.48-py3.5.egg/yowsup/layers/protocol_media/layer.py", line 47, in recvMessageStanza
    self.toUpper(entity)
  File "/usr/lib/python3.5/site-packages/yowsup2-2.4.48-py3.5.egg/yowsup/layers/__init__.py", line 75, in toUpper
    self.__upper.receive(data)
  File "/usr/lib/python3.5/site-packages/yowsup2-2.4.48-py3.5.egg/yowsup/layers/interface/interface.py", line 78, in receive
    self.entity_callbacks[entityType](entity)
  File "/usr/lib/python3.5/site-packages/yowsup2-2.4.48-py3.5.egg/yowsup/demos/cli/layer.py", line 517, in onMessage
    messageOut = self.getMediaMessageBody(message)
  File "/usr/lib/python3.5/site-packages/yowsup2-2.4.48-py3.5.egg/yowsup/demos/cli/layer.py", line 543, in getMediaMessageBody
    return self.getDownloadableMediaMessageBody(message)
  File "/usr/lib/python3.5/site-packages/yowsup2-2.4.48-py3.5.egg/yowsup/demos/cli/layer.py", line 548, in getDownloadableMediaMessageBody
    filename = "%s/%s%s"%(tempfile.gettempdir(),message.getId(),message.getExtension())
  File "/usr/lib/python3.5/site-packages/yowsup2-2.4.48-py3.5.egg/yowsup/layers/protocol_media/protocolentities/message_media_downloadable.py", line 78, in getExtension
    return MimeTools.getExtension(self.mimeType)
  File "/usr/lib/python3.5/site-packages/yowsup2-2.4.48-py3.5.egg/yowsup/common/tools.py", line 197, in getExtension
    raise Exception("Unsupported/unrecognized mimetype: "+mimetype);
Exception: Unsupported/unrecognized mimetype: audio/aac
`

Crashing on audio files? I'm afraid of fixing this and falling on the noAck trap again :'(

**Comment by freelo** [comment]
That is strange. According to `yowsup/common/mime.types`, audio/aac should be recognized. Workaround: make your code guess the extension. ;)

**Comment by Gab0** [comment]
True. But check your lib folder, and check the .egg file for yowsup. mime.types isn't there. I fixed this and everything works here now :3

**Comment by jlguardi** [comment]
Fixed with related commit (3db22d1)

**Comment by Gab0** [comment]
Thanks jlguardi, but it didn't fix.

SOURCES.txt: 
`setup.py
yowsup-cli
yowsup/__init__.py
yowsup/common/__init__.py
yowsup/common/constants.py
yowsup/common/optionalmodules.py
yowsup/common/tools.py
yowsup/common/http/__init__.py
yowsup/common/http/httpproxy.py
yowsup/common/http/test_warequest.py
yowsup/common/http/warequest.py
yowsup/common/http/waresponseparser.py
yowsup/demos/__init__.py
yowsup/demos/cli/__init__.py
yowsup/demos/cli/cli.py
....`

mime.types is still not in the .egg

**Comment by jlguardi** [comment]
Are you sure that you have downloaded from jlguardi/yowsup/master? I've downloaded and the setup.py installs it.
