### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd5...

### ISSUE THREAD

**Issue by RodrigoRVieira** [tgalal/yowsup#1490]
Hello everyone,

Are you able yo use this API right now?

It can successfully send messages, but receiving is not possible...

Thank you

**"return plaintext.decode()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd5 in position 3: invalid"**

**Comment by freelo** [comment]
Usually this strategy works: if `plaintext` is str, decode it as utf-8; if it is unicode already, just leave it. What is `type(plaintext)` here? And where does it come from? Is it the message body?

**Comment by McBacker** [comment]
"Is it the message body?"

I believe so... Are u running this lib smoothly? What is your environment? Latest Yowsup? Python version?

Thank you

**Comment by sattva1** [comment]
Are you running it with Python3 by a chance? It might be your problem: #1484.

**Comment by McBacker** [comment]
Applied the "fix" below and it works... at least for text messages.

https://github.com/tgalal/yowsup/issues/1356

**Comment by victorpachecolopez** [comment]
Not work for me!
Use Python 3.5, what version of python use?

**Comment by sattva1** [comment]
It should work correctly with Python 2.7.

**Comment by just10minutes** [comment]
Did not work for me either. Python 3.5  @victorpachecolopez  any luck on resolving this?

**Comment by jlguardi** [comment]
First of all, report which version are you using: 2.4.102 / wa16, jlguardi/master, jlguardi/devel. 
If you can reproduce this issue, print the string that produces the issue and check if skiping 3 chars fix the issue s=s[3:]. If works, it is the padding issue (reported and fix several times)

**Comment by just10minutes** [comment]
below is my current version, i installed yowsup using pip

$ yowsup-cli demos -v
yowsup-cli v2.0.15
Using yowsup v2.4.102

i will try your suggestion and get back to you

**Comment by jlguardi** [comment]
This is the padding issue fixed with #1390

**Comment by just10minutes** [comment]
Actually i have made that change but still it did not resolve the issue.

Please confirm which version i should be using?
tgalal/yowsup?  or jlguardi/yowsup   
why i am asking this because there is a huge difference between this file on both repositories
yowsup/yowsup/layers/axolotl/layer.py

**Comment by voltagex** [comment]
The pull request has been deleted - so what's supposed to be fixed here? @jlguard? / @tgalal?

**Comment by tgalal** [comment]
31a9871
