### ISSUE TITLE
Getting "status":"fail","reason":"old_version"\n' status: b'fail' reason: b'old_version' when registering using yowsup-cli

### ISSUE THREAD

**Issue by Len-nart** [tgalal/yowsup#1747]
I've implemented #1725 and #1716, referencing at #1729 solution.

using this line:
`yowsup-cli registration --requestcode sms --phone 628XXXXXXXXXX --cc 62 --mcc 510 --mnc 01
` 
gives me these output:
`INFO:yowsup.common.http.warequest:b'{"status":"fail","reason":"old_version"}\n'`
`status: b'fail'`
`reason: b'old_version'`

Also, changing the default to android doesn't work as solution in yowsup/env/env.py.

**Comment by manelmolina** [comment]
I'm having the same issue, after change the default value to android on env.py I also modify env_android.py to set version to 2.16.225 (current whatsapp version) but now the error message is "bad token" I think that is also necesary to set a new KEY on the same file but I don't know how to get it.

**Comment by manelmolina** [comment]
Solved:

- On env.py set default to "s40" and on env_S40 set the right key:

https://github.com/schoerg/yowsup/commit/d1274dcac38b4e93d48077a8789b4214a39e1960

**Comment by albert-chin** [comment]
@manelmolina 
> I'm having the same issue, after change the default value to android on env.py I also modify env_android.py to set version to 2.16.225 (current whatsapp version) but now the error message is "bad token" I think that is also necesary to set a new KEY on the same file but I don't know how to get it.

If you want to imitate to be a recent client, 
more than the version number have to be changed.
See, for example [this](https://github.com/schoerg/yowsup/commit/42261bf5aaa09db195d02e363c8eb1c6070822ca)

**Comment by jlguardi** [comment]
Update to latest master where version number and token are fixed.

**Comment by thobhanifreddy** [comment]
I am still getting same error! 

`INFO:yowsup.common.http.warequest:b'{"login":"917778912370","status":"fail","reason":"old_version"}\n'
status: b'fail'
reason: b'old_version'
login: b'917778912370'`

**Comment by coollorenzo** [comment]
same here 
input:
`yowsup-cli registration -p 12028525xxx -C 1 -m 310 -r voice`
output:
`INFO:yowsup.common.http.warequest:b'{"login":"12028525xxx","status":"fail","reason":"old_version"}\n'
`

**Comment by Bluscream** [comment]
im getting the same error

**Comment by dzhaugasharov** [comment]
Change the constant's value to "android" in the file yowsup/env/env.py to folowing:
`DEFAULT = "android"`
