### ISSUE TITLE
{"status":"fail","reason":"old_version"}

### ISSUE THREAD

**Issue by huilen** [tgalal/yowsup#1869]
Hi guys,

I'm getting the "old version" error when requesting a new code:

$ yowsup-cli registration --requestcode sms --phone 54911xxxxxxxx --cc 54 --mcc 722 --mnc 340 -d
yowsup-cli  v2.0.15
yowsup      v2.5.0

Copyright (c) 2012-2016 Tarek Galal
http://www.openwhatsapp.org

This software is provided free of charge. Copying and redistribution is
encouraged.

If you appreciate this software and you would like to support future
development please consider donating:
http://openwhatsapp.org/yowsup/donate

DEBUG:yowsup.env.env:Env not set, setting it to s40
DEBUG:yowsup.env.env:Current env changed to s40 
DEBUG:yowsup.common.http.warequest:{'Accept': 'text/json', 'User-Agent': 'WhatsApp/2.16.9 S40Version/14.26 Device/Nokia-302'}
DEBUG:yowsup.common.http.warequest:cc=54&in=91130191534&lc=GB&lg=en&sim_mcc=722&sim_mnc=340&mcc=722&mnc=340&method=sms&mistyped=6&network_radio_type=1&simnum=1&s=&copiedrc=1&hasinrc=1&rcmatch=1&pid=4638&rchash=0605829586ba80abb617c6a57f02db15b96021644b28671632193a4fcb078e67&anhash=%F0tjT%22%B2%9B%2C%00x%5DZ%C8%3AB%0E%EC%5E%40%09&extexist=1&extstate=1&token=3a0e89d35a6be026706db1058d71b164&id=%24B%03%60j%2F%F9%F0%A4%FCUrb%A9%161%7F%A4%98a
DEBUG:yowsup.common.http.warequest:Opening connection to v.whatsapp.net
DEBUG:yowsup.common.http.warequest:Sending GET request to /v2/code?cc=54&in=91130191534&lc=GB&lg=en&sim_mcc=722&sim_mnc=340&mcc=722&mnc=340&method=sms&mistyped=6&network_radio_type=1&simnum=1&s=&copiedrc=1&hasinrc=1&rcmatch=1&pid=4638&rchash=0605829586ba80abb617c6a57f02db15b96021644b28671632193a4fcb078e67&anhash=%F0tjT%22%B2%9B%2C%00x%5DZ%C8%3AB%0E%EC%5E%40%09&extexist=1&extstate=1&token=3a0e89d35a6be026706db1058d71b164&id=%24B%03%60j%2F%F9%F0%A4%FCUrb%A9%161%7F%A4%98a
INFO:yowsup.common.http.warequest:{"status":"fail","reason":"old_version"}

status: fail
reason: old_version

Is it because Whatsapp version has been updated?

Regards,

**Comment by nedimhx** [comment]
Check this https://github.com/tgalal/yowsup/issues/1861

**Comment by huilen** [comment]
Thanks, it worked, but now (with the new version) I can't receive nor send messages any more:

$ yowsup-cli demos -l 5491130190478:T8Vj1hwDULFbPj6i9kL0+ECrch8= -e
yowsup-cli  v2.0.15
yowsup      v2.5.0

Copyright (c) 2012-2016 Tarek Galal
http://www.openwhatsapp.org

This software is provided free of charge. Copying and redistribution is
encouraged.

If you appreciate this software and you would like to support future
development please consider donating:
http://openwhatsapp.org/yowsup/donate


It just ends there. The same happens when trying to send a message:

$ yowsup-cli demos -l 5491130190478:T8Vj1hwDULFbPj6i9kL0+ECrch8= -s 5491125698065 hola
yowsup-cli  v2.0.15
yowsup      v2.5.0

Copyright (c) 2012-2016 Tarek Galal
http://www.openwhatsapp.org

This software is provided free of charge. Copying and redistribution is
encouraged.

If you appreciate this software and you would like to support future
development please consider donating:
http://openwhatsapp.org/yowsup/donate

The process just finishes there.

I noted that the call to stack.loop() returns immediatly, instead of blocking the process as before.

Any comment?

Thanks.

**Comment by gushome7** [comment]
Use env_s40 instead android

**Comment by moh1122** [comment]
done

**Comment by huilen** [comment]
I tried with env_s40 and I still have the problem. Any idea?

**Comment by jlguardi** [comment]
Use env for s40 with version 2.16.11. You can get it from my master.

**Comment by huilen** [comment]
Thanks for the reply. With your master I'm getting an authentication error:

```
(.venv_jlguardi)root@vm-1539111:~/octopione_mw_oneline# YowsupEnv=env_s40 yowsup-cli demos -l 54911301XXXX:T8Vj1hwDULFbPj6i9kL0+ECrch8= -s 54911301XXXX holaaaaaaaaa
yowsup-cli  v2.0.15
yowsup      v2.5.0

Copyright (c) 2012-2016 Tarek Galal
http://www.openwhatsapp.org

This software is provided free of charge. Copying and redistribution is
encouraged.

If you appreciate this software and you would like to support future
development please consider donating:
http://openwhatsapp.org/yowsup/donate


Authentication Error: not-authorized
```

**Comment by jlguardi** [comment]
Just use my env_s40.py with tgalal master.

**Comment by rravishankar** [comment]
Mine is working with the above suggested changes by nedihmx but finally my message is not received. This is quite frustrating after going through all the steps. Can anyone help? Is this working for someone now or has it been  blocked? 

Here's the debug output:

`ravishankar@ravishankar-desktop:~/Whatsapp$ sudo yowsup-cli demos --send 919xxxxx "Test message" --config yowsup-cli.config -d`
yowsup-cli  v2.0.15
yowsup      v2.5.0

Copyright (c) 2012-2016 Tarek Galal
http://www.openwhatsapp.org

This software is provided free of charge. Copying and redistribution is
encouraged.

If you appreciate this software and you would like to support future
development please consider donating:
http://openwhatsapp.org/yowsup/donate


DEBUG:yowsup.env.env:Env not set, setting it to android
DEBUG:yowsup.env.env:Current env changed to android 
DEBUG:yowsup.stacks.yowstack:Initializing stack
DEBUG:yowsup.stacks.yowstack:Constructed Network Layer
DEBUG:yowsup.stacks.yowstack:Constructed Stanza Regulator Layer
DEBUG:yowsup.stacks.yowstack:Constructed Crypt Layer
DEBUG:yowsup.stacks.yowstack:Constructed Coder Layer
DEBUG:yowsup.stacks.yowstack:Constructed Logger Layer
DEBUG:yowsup.stacks.yowstack:Constructed <yowsup.layers.axolotl.layer_control.AxolotlControlLayer object at 0x7fc2d808e510>
DEBUG:yowsup.stacks.yowstack:Constructed Axolotl Layer - <yowsup.layers.axolotl.layer_receive.AxolotlReceivelayer object at 0x7fc2d807dd90>
DEBUG:yowsup.stacks.yowstack:Constructed Authentication Layer - Messages Layer - Receipt Layer - Ack Layer - Presence Layer - Ib Layer - Iq Layer - notification Ib Layer - Iq Layer - Chatstate Layer - call Layer - Groups Iq Layer - Media Layer - Privacy Layer - Profiles Layer
DEBUG:yowsup.stacks.yowstack:Constructed Interface Layer
DEBUG:yowsup.layers.network.layer:Connecting to e14.whatsapp.net:443
DEBUG:yowsup.layers.logger.layer:tx:
<stream:features>
</stream:features>

DEBUG:yowsup.layers.logger.layer:tx:
<auth passive="true" user="919xxxx" mechanism="WAUTH-2">
</auth>

DEBUG:yowsup.layers.logger.layer:rx:
<stream:features>
</stream:features>

DEBUG:yowsup.layers.logger.layer:rx:
<challenge>
������XXXXXXXXXXX
HEX:c0b2fdc8c2f504371XXXXXXXXXXXXX
</challenge>

DEBUG:yowsup.layers.logger.layer:tx:
<response xmlns="urn:ietf:params:xml:ns:xmpp-sasl">

x�=т=R��-��WՆ����!pMK�G�
X"�+h����˺
����+���z�IXXXXXXXXXXXXXX
HEX:0c78c43dd1823d52d6e02de2b157d586f5f4b6aa21704d4b1ef947b00a462215f72b68a9b6a1c2cXXXXXXXXXXXXXXXX
</response>

DEBUG:yowsup.layers.network.layer:Disconnected, reason: Connection Closed

**Comment by Kurill** [comment]
you have banned

**Comment by rravishankar** [comment]
Ok, I don't understand why. I just tried sending two messages and both times I got similar result. Can anyone please explain. Thanks

**Comment by jlguardi** [comment]
@rravishankar You aren't banned but you are using android env which can't connect. Use s40 instead.

**Comment by Subhajit321** [comment]
https://v.whatsapp.net
![image](https://user-images.githubusercontent.com/39081525/42377453-fae1f5fe-8140-11e8-8400-b6fddb65295b.png)
