### ISSUE TITLE
CLI Error: AttributeError: 'list' object has no attribute 'clear'

### ISSUE THREAD

**Issue by redrux** [tgalal/yowsup#2668]
I registered again with **yowsup3**. And then pasted credentials to config.json. I'm trying to log in but giving some error right below:

` ./yowsup-cli demos --yowsup --config config.json
yowsup-cli  v3.0.0
yowsup      v3.0.0

Copyright (c) 2012-2019 Tarek Galal
http://www.openwhatsapp.org

This software is provided free of charge. Copying and redistribution is
encouraged.

If you appreciate this software and you would like to support future
development please consider donating:
http://openwhatsapp.org/yowsup/donate

Yowsup Cli client
==================
Type /help for available commands

[offline]:/L
I 2019-04-23 13:55:38,060 yowsup.layers.network.layer - Connecting to e3.whatsapp.net:443
I 2019-04-23 13:55:38,201 yowsup.axolotl.manager - Generating 812 prekeys
I 2019-04-23 13:55:38,355 yowsup.axolotl.manager - Storing 812 prekeys
I 2019-04-23 13:55:39,013 yowsup.axolotl.manager - Loaded 812 unsent prekeys
Traceback (most recent call last):
  File "/home/renekton/Desktop/yowsup/yowsup/layers/network/dispatcher/dispatcher_socket.py", line 42, in connectAndLoop
    self.connectionCallbacks.onRecvData(data)
  File "/home/renekton/Desktop/yowsup/yowsup/layers/network/layer.py", line 82, in onRecvData
    self.receive(data)
  File "/home/renekton/Desktop/yowsup/yowsup/layers/network/layer.py", line 85, in receive
    self.toUpper(data)
  File "/home/renekton/Desktop/yowsup/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/home/renekton/Desktop/yowsup/yowsup/layers/noise/layer_noise_segments.py", line 39, in receive
    self.toUpper(bytes(data))
  File "/home/renekton/Desktop/yowsup/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/home/renekton/Desktop/yowsup/yowsup/layers/noise/layer.py", line 149, in receive
    self._flush_incoming_buffer()
  File "/home/renekton/Desktop/yowsup/yowsup/layers/noise/layer.py", line 137, in _flush_incoming_buffer
    self.toUpper(self._wa_noiseprotocol.receive())
  File "/home/renekton/Desktop/yowsup/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/home/renekton/Desktop/yowsup/yowsup/layers/coder/layer.py", line 21, in receive
    self.toUpper(node)
  File "/home/renekton/Desktop/yowsup/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/home/renekton/Desktop/yowsup/yowsup/layers/logger/layer.py", line 14, in receive
    self.toUpper(data)
  File "/home/renekton/Desktop/yowsup/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/home/renekton/Desktop/yowsup/yowsup/layers/axolotl/layer_control.py", line 32, in receive
    self.toUpper(protocolTreeNode)
  File "/home/renekton/Desktop/yowsup/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/home/renekton/Desktop/yowsup/yowsup/layers/__init__.py", line 194, in receive
    s.receive(data)
  File "/home/renekton/Desktop/yowsup/yowsup/layers/axolotl/layer_receive.py", line 39, in receive
    self.toUpper(protocolTreeNode)
  File "/home/renekton/Desktop/yowsup/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/home/renekton/Desktop/yowsup/yowsup/layers/__init__.py", line 194, in receive
    s.receive(data)
  File "/home/renekton/Desktop/yowsup/yowsup/layers/__init__.py", line 130, in receive
    recv(node)
  File "/home/renekton/Desktop/yowsup/yowsup/layers/auth/layer_authentication.py", line 63, in handleSuccess
    self.broadcastEvent(successEvent)
  File "/home/renekton/Desktop/yowsup/yowsup/layers/__init__.py", line 202, in subBroadcastEvent
    self.broadcastEvent(yowLayerEvent)
  File "/home/renekton/Desktop/yowsup/yowsup/layers/__init__.py", line 103, in broadcastEvent
    self.__lower.broadcastEvent(yowLayerEvent)
  File "/home/renekton/Desktop/yowsup/yowsup/layers/__init__.py", line 98, in broadcastEvent
    if self.__lower and not self.__lower.onEvent(yowLayerEvent):
  File "/home/renekton/Desktop/yowsup/yowsup/layers/__init__.py", line 109, in onEvent
    return self.event_callbacks[eventName](yowLayerEvent)
  File "/home/renekton/Desktop/yowsup/yowsup/layers/axolotl/layer_control.py", line 59, in onAuthed
    self._unsent_prekeys.clear()
AttributeError: 'list' object has no attribute 'clear'
E 2019-04-23 13:55:39,775 yowsup.layers.network.dispatcher.dispatcher_socket - 'list' object has no attribute 'clear'
general: Disconnected: 
`

@tgalal

**Comment by tgalal** [comment]
it's python2-related issue. I've fixed it on master and will release an update soon. You could in the meantime use yowsup from master or try again with python3

**Comment by redrux** [comment]
@tgalal Thank you but problem is still continuing

renekton@ubuntu:~/Desktop/yowsup$ Already up to date.

**Comment by tgalal** [comment]
fixed in [v3.1.0](https://github.com/tgalal/yowsup/releases/tag/v3.1.0)
